services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=recrutamento'
      - 'MYSQL_PASSWORD=gomes'
      - 'MYSQL_ROOT_PASSWORD=gomes'
      - 'MYSQL_USER=andrew'
    ports:
      - '3306:3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'