CREATE TABLE IF NOT EXISTS technology (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    vacancy_id BIGINT NOT NULL,
    technology VARCHAR(30) NOT NULL,
    FOREIGN KEY (vacancy_id) REFERENCES vacancies(id) ON DELETE CASCADE
);
